<?php 
/**
 * Cronjob Scheduler Include File
 *
 * This page allows you to create Cronjob Scheduler custom actions
 * through the WordPress admin. Actions can also be created within
 * theme files or other PHP files throughout your WordPress install.
 *
 * Do not edit this file unless you have a good understanding of PHP, 
 * saving this with invalid code can render your WordPress install inoperable
 * until you can fix the issue using FTP or another file editing utility.
**/

require_once( ABSPATH . 'wp-includes/MerlotApi.php' );
require_once( ABSPATH . 'wp-includes/WiseWireImportCategories.php' );


function update_list_featured_authors () {

	global $wpdb;

	/* DELETE FEATURED 2 HOURS AFTER THEY WERE ADDED*/
	$sql = $wpdb->prepare("DELETE FROM `wp_cache_featured` WHERE `date_creation` <  DATE_SUB(NOW(),INTERVAL 2 HOUR)");				
	$wpdb->query($sql);
    
} add_action('update_list_featured_authors', 'update_list_featured_authors');


function get_merlot_materials () {

	$merlot_api = new MerlotApi();	
	$merlot_api->clearDataFromMerlot();
	$merlot_api->LoadDataFromMerlot();
    
} add_action('get_merlot_materials', 'get_merlot_materials');


function get_platform_categories_data () {
	
	$categoriesApi = new WiseWireImportCategories();			
	$categoriesApi->download();
	$categoriesApi->SaveInCategoriesTableSearch();
    
} add_action('get_platform_categories_data', 'get_platform_categories_data');





